### ISSUE TITLE
Release v0.5.1: Python and Go FhirProto parsing, printing, and validating libraries missing

### ISSUE THREAD

**Issue by sam-virta** [google/fhir#10]
Release v0.5.1 mentions FhirProto parsing, printing, and validating libraries in Python and Go but they are not present. 

We've implemented a Go version ourselves and would love to deprecate it.

**Comment by nickgeorge** [comment]
Stay tuned!  those will be in the .6 release.  The code is mostly written,
butr we've done a lot of refactoring as well since the last release, so we
wanted to do a minor release first, and .6 will have the new functionality
(including the python and go support)

**Comment by jamesthompson** [comment]
Will it be possible to prevent the java / cc / python / go library builds? It would be nice to just have the rules_proto targets built in my use case.

**Comment by nickgeorge** [comment]
Hey Sam - take a look at https://github.com/google/fhir/releases/tag/v0.5.2 - this adds Go Parsing and Printing, with an example here: https://github.com/google/fhir-examples/blob/master/go/google/fhir_examples/parse_patients.go

I'm gonna close this issue for now, but if you try it out, I'd love to hear how it goes!  Please open more issues if you run into them, I'm really making an effort to be more responsive here :)
