### ISSUE TITLE
in resources/patient.proto  the  birth_date  is inconsist with std schemema definition , birthDate

### ISSUE THREAD

**Issue by niupanyu** [google/fhir#11]
https://www.hl7.org/fhir/patient.html

**Comment by nikklassen** [comment]
The convention for naming proto fields is to use snake_case rather than camelCase. However, when you serialize it to JSON it will use camelCase.

**Comment by niupanyu** [comment]
thanks, that's the pb3 's constraint.


> The convention for naming proto fields is to use snake_case rather than camelCase. However, when you serialize it to JSON it will use camelCase.
