### ISSUE TITLE
Consider tagging submodule "go"?

### ISSUE THREAD

**Issue by Rick-xuy** [google/fhir#137]
I found that packages, say `github.com/google/fhir/go/proto/google/fhir/proto/annotations_go_proto`, are placed in submodule `github.com/google/fhir/go` instead of root module. <br>
However, it seems that submodule `github.com/google/fhir/go` is not tagged. According to [go docs](https://go.dev/doc/modules/managing-source#multiple-module-source), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/google/fhir/go/proto/google/fhir/proto/annotations_go_proto`, downstream would depends on **pseudo-version** of module `github.com/google/fhir/go`.
```
github.com/google/fhir/go v0.0.0-20230201040735-41722f15f676
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `go/v0.0.1`, `go/v0.7.4`etc, so that other project can use tag to import this module in go.mod.

**Comment by nikklassen** [comment]
This sounds totally reasonable, our team isn't super familiar with everything we should do to properly publish Go packages. I'll look into making this change

**Comment by nikklassen** [comment]
@suyashkumar we should add this to the release process
