### ISSUE TITLE
Accepting JSON from standard FHIR server

### ISSUE THREAD

**Issue by justinfargnoli** [google/fhir#14]
Could use this library to generate a FHIR client library which accepts JSON from a FHIR server which is not using gRPC?

I'm new to protocol buffers and gRPC and I've been looking into this for a couple days, but I've been having hard time finding a definitive answer. Thank you for your help in advance!

**Comment by jamesthompson** [comment]
@justinfargnoli This repo currently has support for parsing FHIR JSON in Java, C++ and Golang into the generated protobuf models. You can then use those models to manipulate the data and re-serialize back to JSON should you need to.

**Comment by justinfargnoli** [comment]
That's great to know, thank you! 

My team and I are using Dart and Flutter, so I think we'll have to go another route. 

If the contributors to this repo are considering or are currently building this functionality for Dart, then we'd love to use it!
