### ISSUE TITLE
[Go] How to parse profile

### ISSUE THREAD

**Issue by jandauz** [google/fhir#154]
I want to use the [US Core profile](https://github.com/google/fhir/blob/master/go/proto/google/fhir/proto/r4/uscore_go_proto/uscore.pb.go). However, I don't see any way of parsing a US Core Patient JSON into a `USCorePatientProfile`. The `jsonformat` unmarshaller always returns an instance of `*r4pb.ContainedResource`.

Is there a way to [convert](https://github.com/google/fhir/blob/master/cc/google/fhir/r4/profiles.h#L51) from one profile to another like in C++? Or unmarshal directly into a `USCorePatientProfile`?

**Comment by nikklassen** [comment]
This isn't functionality that we've built for the Go parser. We try to have some consistency between the different languages in this repo, but they are written by different teams with different use cases. If you want specialized protos for profiles I recommend mapping the ContainedResource yourself, maybe the C++ code will offer some guidance on how to do that

**Comment by nithin36543654** [comment]
@jandauz were you able to figure out ?

**Comment by jandauz** [comment]
> @jandauz were you able to figure out ?

Sorry no. We decided that the effort wasn't worth it and we went with a different approach for validating against a profile.
