### ISSUE TITLE
Overlapping filenames causing issues on case-insensitive filesystems.

### ISSUE THREAD

**Issue by tmc** [google/fhir#17]
The following files have collisions on case-insensitive filesystems:

```
spec/hl7.fhir.core/3.0.1/package/CodeSystem-example.json
spec/hl7.fhir.core/3.0.1/package/CodeSystem-list-example-codes.json
spec/hl7.fhir.core/3.0.1/package/ValueSet-example-expansion.json
spec/hl7.fhir.core/3.0.1/package/ValueSet-example-intensional.json
spec/hl7.fhir.core/3.0.1/package/ValueSet-list-example-codes.json
```

This makes including this repository as a submodule inconvenient as the submodule will always report a dirty filesystem state.

**Comment by nickgeorge** [comment]
yup, you're 100% correct - I have a fix it that's almost done, should get that in soon.  sorry!

As a side note - we're working on setup scripts that help setting up the dependencies on different platforms, stay tuned!
