### ISSUE TITLE
google.fhir Python PIP installable

### ISSUE THREAD

**Issue by gitpushdashf** [google/fhir#19]
Are there any plans to make a Python PIP release of google.fhir? Haven't found any existing ones, just for JSON. Would be very handy.

Thank you!

**Comment by nickgeorge** [comment]
Yup, stay tuned... we're *very* close to a major python release which will add a lot of the functionality that currently exists in other languages to Python (e.g., parsing, printing, and validating).  This will also make the code available in pypi as PIP packages.

**Comment by gitpushdashf** [comment]
Fantastic! Looking forward to it.

**Comment by edybk** [comment]
Looking forward to it as well

**Comment by nickgeorge** [comment]
Update on this: We've resolved the last major blocker for this.  Look for this within the next week or so!

**Comment by gitpushdashf** [comment]
Thank you @nickgeorge ! You'll make my day when this is a PIP installable. Really looking forward to it.

**Comment by Cam2337** [comment]
Hi @gitpushdashf,

I've been working with @nickgeorge on this release, and am happy to let you know that as of 0.6.0, there is a pypi package available for google-fhir for macOS/Linux Python >=3.6, <3.9! Per @nickgeorge's comments, this brings parsing, printing, and basic resource validation to native Python3 for FHIR STU3 and FHIR R4. For more information on the pypi package, see: https://pypi.org/project/google-fhir/.

You can see https://github.com/google/fhir-examples/tree/master/py/google/fhir_examples for some additional Python FHIR examples around `json_format` and resource validation.

Note that we also have full `bazel` support, and so if you would rather, you can simply clone the repository, and `bazel build/test` as needed. We strongly recommend performing this in a `venv` to help ensure that the execution of the Python interpreter by `bazel` is hermetically-sealed.

We're continuing to work on adding stronger validation support (akin to what is available in C++ with `fhir_path`), as well as continuing to profile+test+iterate.

Going to mark this issue as "closed" for now, but feel free to re-open or create a new issue if you have any questions/comments/concerns. We'd love your feedback and are excited to keep working on this with the community! :)

**Comment by gitpushdashf** [comment]
Thank you so much! We are looking forward to trying it out.

The only other thing I can think of is mypy stubs. We use them heavily and I'm not sure yet if you are generating those. We should be able to generate them if need be, but they are helpful for typing.

**Comment by Cam2337** [comment]
I'm not _super_ familiar with mypy stubs, but it seems like their primary use case is for type information for third party modules whose authors haven't added type hints (https://mypy.readthedocs.io/en/stable/stubs.html).

For `google-fhir`, we've added type hints for all public (and internal) API. We validate this against the [pytype](https://github.com/google/pytype) type checker. I'll poke around `mypy` to ensure that types are being properly validated there as well!

**Comment by gitpushdashf** [comment]
Ah, great. We've been using this to generate the stubs right from the protos: https://github.com/dropbox/mypy-protobuf

**Comment by Cam2337** [comment]
Awesome, I'll check it out. Seems like this could be useful for the generated protos!

**Comment by anthem-bmk** [comment]
It looks like there are at least some typehints already, but I think in order for type checkers to pick it up you need to include a `py.typed` file (just an empty file) in the root (e.g. `touch google/fhir/py.typed`): https://www.python.org/dev/peps/pep-0561/#packaging-type-information

You may also need to modify setup.py to make sure it includes that file in the package.

**Comment by Cam2337** [comment]
Thanks @anthem-bmk!

I have some internal work going to add the `py.typed` to ensure that `google/fhir` exposes our in-line type annotations per PEP0561. Additionally, I'm validating against both `pytype` and `mypy`, the former is creating some issues that I'm discussing /w the `pytype` team. Finally, I also have some WIP to create the `.pyi` stub files for our generated protobuf classes, though I'm exploring the best way to distribute these (e.g. via extras, etc.). We'll get these out as soon as they're ready! :)

**Comment by gitpushdashf** [comment]
The typing is working great, thank you!

**Comment by Cam2337** [comment]
Glad to hear it @gitpushdashf!!

We're continuing to profile+improve performance, etc., along with some bigger ticket items as well. Please be sure to reach out if you have other things you'd like to see like this! :)
