### ISSUE TITLE
Python json -> protobuf "cannot be parsed as a reference"

### ISSUE THREAD

**Issue by gitpushdashf** [google/fhir#24]
The latest Synthea gives different output. An older version works fine for me, however the latest results in:

`ValueError: String 'Practitioner?identifier=http://hl7.org/fhir/sid/us-npi|9999999959' cannot be parsed as a reference.`

I can write up a code sample if need be.

This is using Synthea from master: https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar

It looks like they have some versions released more recently, I will try those.

**Comment by Cam2337** [comment]
Interesting, yes a code sample would be fantastic!

> ...An older version works fine for me, however the latest results in...

Just so I'm clear, you're saying an older Synthea works o.k.? What's the version that was working for you?

Thanks for bringing it to our attention!

**Comment by gitpushdashf** [comment]
Yeah, an older one works fine. Synthea wasn't tagging releases for over a year and the only (easy) option was downloading the .jar made from master.

https://github.com/synthetichealth/synthea/releases

Now it turns out that in September they made releases, but those releases seem to be build for openjdk12 and not openjdk8... https://github.com/synthetichealth/synthea/issues/813

Anyway, here's a snippet of the new output.

```
            "who": {
              "reference": "Practitioner?identifier=http://hl7.org/fhir/sid/us-npi%7C9999948299",
              "display": "Dr. Dorothea248 Huel628"
            },
            "onBehalfOf": {
              "reference": "Organization?identifier=https://github.com/synthetichealth/synthea%7Cde004a50-64ca-37eb-bf70-d5589fa7999f",
              "display": "PCP149816"
            }
          },
          {
            "type": {
              "coding": [
                {
                  "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-provenance-participant-type",
                  "code": "transmitter",
                  "display": "Transmitter"
                }
              ],
              "text": "Transmitter"
            },
            "who": {
              "reference": "Practitioner?identifier=http://hl7.org/fhir/sid/us-npi%7C9999948299",
              "display": "Dr. Dorothea248 Huel628"
            },
            "onBehalfOf": {
              "reference": "Organization?identifier=https://github.com/synthetichealth/synthea%7Cde004a50-64ca-37eb-bf70-d5589fa7999f",
              "display": "PCP149816"
            }
          }
        ]
      },
      "request": {
        "method": "POST",
        "url": "Provenance"
      }
    }
  ]
}
```

Thanks for getting back to me. Let me come up with a code snippet.

**Comment by gitpushdashf** [comment]
Ok, hopefully this helps. I made/activated a virtualenv, pip3 installed google-fhir and requests, then ran the script in an empty directory.

[synthea.py.txt](https://github.com/google/fhir/files/5461846/synthea.py.txt)

Thanks!

**Comment by Cam2337** [comment]
Thanks for the details! I believe that these patterns started being introduced in Synthea with SHA: `b262437bce35bfec4e485e150832242b5a68581a` ([link](https://github.com/synthetichealth/synthea/commit/b262437bce35bfec4e485e150832242b5a68581a)).

Since `Uri` has a really permissive pattern (`\S*`; [source](https://www.hl7.org/fhir/datatypes.html#uri)), it seems like we're potentially being too strict in `references.py` if we're unable to [split the relative reference](https://github.com/google/fhir/blob/master/py/google/fhir/references.py#L70).

Will look into correcting this behavior so that we're taking appropriate action.

**Comment by Cam2337** [comment]
Circling back on this -- the change was trivial but it required additional work to some things downstream. I have a fix internally now that's going through review.

In the meantime as we discussed you should be able to avoid any problematic Synthea by sticking to versions earlier than `b262437bce35bfec4e485e150832242b5a68581a`. Additionally, as a temporary workaround I believe you can instruct Synthea to not use `transaction_bundle`, which should avoid these logical Reference URLs, e.g.:
```
~/synthea$ ./run_synthea Massachusetts -p 10
~/synthea$ grep -R '"reference":' ./output/fhir/ | grep -E '[A-Z][a-z]+\?.*' | wc -l
6010
~/synthea$ rm ./output/fhir/*

~/synthea$ ./run_synthea Massachusetts --exporter.fhir.transaction_bundle false -p 10
~/synthea$ grep -R '"reference":' ./output/fhir/ | grep -E '[A-Z][a-z]+\?.*' | wc -l
0
```
See more at: https://github.com/synthetichealth/synthea/blob/master/src/main/resources/synthea.properties#L18

Appreciate the patience and help in identifying this! :)

**Comment by gitpushdashf** [comment]
Thank you! That's good to know.
