### ISSUE TITLE
py/ subtree accidentally deleted?

### ISSUE THREAD

**Issue by christian-schmaler-snkeos** [google/fhir#299]
All python related files were removed with https://github.com/google/fhir/commit/67732672dfc385d2ddcd8514b211ee1aa042bc71
The entire /py/* subtree is gone.
Judging from the got description this was not intendend? Or is python support silently removed?

**Comment by nikklassen** [comment]
I don't work on the Python code, but it looks like the team moved Python code to https://github.com/google/fhir-py
