### ISSUE TITLE
Idiomatic way of dealing with unknown fields? [golang]

### ISSUE THREAD

**Issue by joshchangNIH** [google/fhir#309]
When parsing the CMS DPC synthetic test files ExplanationOfBenefit and Coverage do not parse cleanly.

err: error at "Coverage": unknown field

error at "ExplanationOfBenefit.extension[0].valueMoney": unknown field
error at "ExplanationOfBenefit.item[0].adjudication[0].amount": unknown field

How are y'all dealing with this? Thanks

**Comment by nikklassen** [comment]
Are the test files publicly accessible? Do you have a link?

**Comment by joshchangNIH** [comment]
From here: https://dpc.cms.gov/data.html

https://bcda.cms.gov/assets/data/ExplanationOfBenefit.ndjson 
https://bcda.cms.gov/assets/data/Coverage.ndjson

Patient parses fine

**Comment by nikklassen** [comment]
It looks like the test files you supplied are STU3 files. The errors you're getting are from trying to parse the resources as R4 resources (Patient has minor (maybe no) changes between versions)
